### ISSUE TITLE
recursive dependency with Module::Build

### ISSUE THREAD

**Issue by karenetheridge** [perl-pod/test-pod#10]
Module::Build has a runtime dependency on Test::Pod.  Test::Pod is built with Module::Build.  On perl 5.22, where Module::Build is not already installed, this results in a circular dependency.

Since there is already a Makefile.PL in the dist (via Module::Build::Compat), this suggests that there aren't any Module::Build-specific features being depended upon, so it should be safe to simply switch to packaging with ExtUtils::MakeMaker.

I can send a patch if you like.

**Comment by karenetheridge** [comment]
ah, belay that... Module::Build doesn't actually declare a prereq on Test::Pod, but it does use it in runtime code.

Still though, if you'd entertain switching to EUMM, I'll happily provide a patch.

**Comment by theory** [comment]
I'm fed up with the whole build/install kerfuffle. They all stink. If you'd like co-maint you can patch and release if you like.

**Comment by karenetheridge** [comment]
heh, sure, I never* met a comaint bit I didn't like :D

*except MongoDB ;)
