### ISSUE TITLE
russian C instead english C

### ISSUE THREAD

**Issue by mishin** [perl-pod/test-pod#12]
Hi,
I have a trouble,
on russian keyboard С rus and C eng 
ord is diffe:
````
perl -E 'say ord() for qw/C С/;'
67
208
````
so, if I write С<chr> with russian 'С' then this is wrong pod
could you add test, that 
If there is a combination of Russian 'С' with '<', so was a mistake

**Comment by theory** [comment]
Not really, no. The Pod::Simple parser [looks for a formatting code](https://github.com/perl-pod/pod-simple/blob/master/lib/Pod/Simple/BlackBox.pm#L1840) matching `[A-Z]<`. Anything else is assumed to just be text. So there is no way to get it to generate a warning or error here (which is what Test::Pod relies on). If you'd like to add something to Pod::Simple to do that, though, feel free to [fork it](https://github.com/perl-pod/pod-simple/fork) and submit a pull request.

**Comment by mishin** [comment]
Thanks for describing, I'll do that.
