### ISSUE TITLE
pod syntax check is limited to lib or blib subfolder

### ISSUE THREAD

**Issue by manwar** [perl-pod/test-pod#14]
Hi,

Recently I came across a package Chart::Plotly v0.0007, looking at it's Kwalitee, one thing it mentioned below:

-------
no_pod_errors
Remove the POD errors. You can check for POD errors automatically by including Test::Pod to your test suite.

Error: Chart-Plotly-0.007/tool/generate.pl -- Around line 100: You forgot a '=back' before '=head2'
-------

I checked the distribution and surprising it does have auto generated pod syntax test script by the plugin Dist::Zilla::Plugin::PodSyntaxTests. However it only looks into folder "lib" or "blib" and ignoring other folders for any perl script with pod doc. In case of Chart::Plotly v0.0007, the perl script is located in the "tools" subfolder and hence gets ignored.

I was wondering if we add any other folder to look into as well when checking pod syntax?

Thanks for your great work.

Best Regards,
Mohammad S Anwar

**Comment by tomhukins** [comment]
I often customise the files I check for POD in, for example by calling `all_pod_files_ok( glob '*' )`.

**Comment by karenetheridge** [comment]
I agree with Tom -- Test::Pod can't guess all the directories that contain files containing pod: e.g. it would have to evaluate the code in Makefile.PL or Build.PL to determine which directory(ies) are installed as .pm or script files. The best thing to do is to explicity pass the directory names.
