### ISSUE TITLE
ignore_dirs with current Test::Pod

### ISSUE THREAD

**Issue by Julien-Elie** [perl-pod/test-pod#9]
Hi,

The all_pod_files function no longer honours the %ignore_dirs hash in Test::Pod:
    https://github.com/perl-pod/test-pod/blob/master/lib/Test/Pod.pm

The feature disappeared in version 1.47, when switching from File::Spec to File::Find:
    https://github.com/perl-pod/test-pod/commit/45b34ba20a1d64e1600c90f54a64234ae198887a

Would it be possible to make it work again?

Thanks again for your work on that Perl module.  We're currently using it to check the POD documentation shipped with the INN news server.
    https://inn.eyrie.org/trac/browser/trunk/tests/docs/pod.t

-- 
Julien ÉLIE

**Comment by theory** [comment]
Great catch, thank you. Would you confirm that d82c2ca fixes this issue for you?

**Comment by Julien-Elie** [comment]
I confirm the above patch fixes the issue for me.  Thanks a lot for your reactivity!

P.-S. : Please note that there is a typo in the new t/pod/CVS/ignored.pod file ("C<%ingore_dirs>").

**Comment by theory** [comment]
Thanks. I released v1.50. Then I fixed the typo. :-)
